<?php
//sub	 bgs		focu	bg	filt	thumb	 slip	li

	$tpl = array(
	
		array(
			'tpltypeid'=>xc01,
			'tplview'=>'cate1.png',
			'tpltypename'=>'xc01_index_wbs',
			'tpldesinfo'=>'',
			'attr'=>'mix thumb focu bgs other wbsxc',
			'sort'=>炫彩01,
		),
		array(
			'tpltypeid'=>1,
			'tplview'=>'cate1.png',
			'tpltypename'=>'101_index',
			'tpldesinfo'=>'',
			'attr'=>'mix thumb focu bgs other',
			'sort'=>1,
		),
		
		array(
			'tpltypeid'=>2,
			'tplview'=>'cate2.png',
			'tpltypename'=>'102_index',
			'tpldesinfo'=>'列表式图片模版，缩略图建议使用150*150或近似尺寸比例的图片。',
			'attr'=>'mix focu bgs lis other',
			'sort'=>2,
		),
		
		array(
			'tpltypeid'=>3,
			'tplview'=>'cate3.png',
			'tpltypename'=>'103_index',
			'tpldesinfo'=>'列表式图片模版，缩略图建议使用150*150或近似尺寸比例的图片。',
			'attr'=>'mix focu bgs lis other',
			'sort'=>3,
		),
				
		array(
			'tpltypeid'=>4,
			'tplview'=>'cate4.png',
			'tpltypename'=>'104_index',
			'tpldesinfo'=>'列表式图片模版，缩略图建议使用150*150或近似尺寸比例的图片。',
			'attr'=>'mix thumb focu bgs lis other',
			'sort'=>4,
		),
						
		array(
			'tpltypeid'=>5,
			'tplview'=>'cate9.png',
			'tpltypename'=>'105_index',
			'tpldesinfo'=>'文字标签式模版，顶部幻灯片尺寸为640*320或近似等比例图片。',
			'attr'=>'mix focu bgs hotel other',
			'sort'=>5,
		),
								
		array(
			'tpltypeid'=>6,
			'tplview'=>'cate106.png',
			'tpltypename'=>'106_index_ydkds',
			'tpldesinfo'=>'',
			'attr'=>'mix focu thumb bgs other',
			'sort'=>6,
		),
										
		array(
			'tpltypeid'=>7,
			'tplview'=>'cate107.png',
			'tpltypename'=>'107_index_2d8si',
			'tpldesinfo'=>'',
			'attr'=>'mix focu thumb bgs other',
			'sort'=>7,
		),

		array(
			'tpltypeid'=>8,
			'tplview'=>'cate108.png',
			'tpltypename'=>'108_index_giw93x',
			'tpldesinfo'=>'',
			'attr'=>'mix filt focu bgs other',
			'sort'=>8,
		),
		
		array(
			'tpltypeid'=>9,
			'tplview'=>'cate109.png',
			'tpltypename'=>'109_index_0fdis',
			'tpldesinfo'=>'',
			'attr'=>'mix focu bgs other',
			'sort'=>9,
		),
				
		array(
			'tpltypeid'=>10,
			'tplview'=>'cate110.png',
			'tpltypename'=>'110_index_2skz7',
			'tpldesinfo'=>'',
			'attr'=>'mix bgs focu thumb other',
			'sort'=>10,
		),
						
		array(
			'tpltypeid'=>11,
			'tplview'=>'cate111.png',
			'tpltypename'=>'111_index_78yus',
			'tpldesinfo'=>'左右图文式模版，顶部幻灯片建议使用尺寸为640*320或近似等比例图片；分类图片建议使用450*300或近似等比例图片，请不要使用高度大于或接近于宽度的图片。',
			'attr'=>'mix bgs focu thumb other',
			'sort'=>11,
		),

		array(
			'tpltypeid'=>12,
			'tplview'=>'cate112.png',
			'tpltypename'=>'112_index_kj7y5',
			'tpldesinfo'=>'',
			'attr'=>'mix bg bgs filt wedding other',
			'sort'=>12,
		),
		
		array(
			'tpltypeid'=>13,
			'tplview'=>'cate113.png',
			'tpltypename'=>'113_index_jks6z',
			'tpldesinfo'=>'',
			'attr'=>'mix bg bgs filt other',
			'sort'=>13,
		),
		
		array(
			'tpltypeid'=>14,
			'tplview'=>'cate114.png',
			'tpltypename'=>'114_index_mnsz6',
			'tpldesinfo'=>'',
			'attr'=>'mix thumb filt bg bgs other',
			'sort'=>14,
		),
		
		array(
			'tpltypeid'=>15,
			'tplview'=>'cate115.png',
			'tpltypename'=>'115_index_ms76x',
			'tpldesinfo'=>'',
			'attr'=>'mix bgs bg filt other',
			'sort'=>15,
		),
		
		array(
			'tpltypeid'=>16,
			'tplview'=>'cate116.png',
			'tpltypename'=>'116_index_ms76x',
			'tpldesinfo'=>'图片式模板，顶部幻灯片建议尺寸为宽640*高320或近似等比例的图片，文字为分类名称及分类描述，名称建议4个字符，描述限制10个字符以内；图片为分类封面，建议尺寸为宽165*高100或近似等比例图片',
			'attr'=>'mix thumb focu bgs other',
			'sort'=>16,
		),
		
		array(
			'tpltypeid'=>17,
			'tplview'=>'cate117.png',
			'tpltypename'=>'117_index_usn3x',
			'tpldesinfo'=>'图标式模板',
			'attr'=>'mix thumb filt bg bgs other',
			'sort'=>17,
		),
		
		array(
			'tpltypeid'=>18,
			'tplview'=>'cate118.png',
			'tpltypename'=>'118_index_jge3',
			'tpldesinfo'=>'图标式模板，顶部幻灯片建议尺寸为宽640*高320或近似等比例的图片。',
			'attr'=>'mix thumb focu bgs other',
			'sort'=>18,
		),
		
		array(
			'tpltypeid'=>19,
			'tplview'=>'cate119.png',
			'tpltypename'=>'119_index_jsg2',
			'tpldesinfo'=>'图标式模板，顶部幻灯片建议尺寸为宽640*高320或近似等比例的图片。',
			'attr'=>'mix focu thumb bgs other',
			'sort'=>19,
		),
		
		array(
			'tpltypeid'=>20,
			'tplview'=>'cate120.png',
			'tpltypename'=>'120_index_pfs9',
			'tpldesinfo'=>'支持二级分类，顶部幻灯片建议尺寸为宽640*高320或近似等比例的图片，幻灯下4个图标为分类管理的前4个分类，图标下第一块内容为第五个分类的分类封面、分类名称及子分类名称，建议尺寸300*300或1:1图片，下面依次类推。',
			'attr'=>'mix focu thumb bgs other',
			'sort'=>20,
		),
		
		array(
			'tpltypeid'=>21,
			'tplview'=>'cate121.png',
			'tpltypename'=>'121_index_eor5w',
			'tpldesinfo'=>'图标式模板，顶部幻灯片建议尺寸为宽640*高320或近似等比例的图片，分类前8个为图标及文字展示，后面分类为图片展示，建议尺寸为宽150*高90或等比例图片。',
			'attr'=>'mix focu bgs thumb other',
			'sort'=>21,
		),

		array(
			'tpltypeid'=>22,
			'tplview'=>'cate122.png',
			'tpltypename'=>'122_index_pgj9d',
			'tpldesinfo'=>'图标式模板，按分类顺序依次展现，有图片显示的分类，图片尺寸建议为宽150*85高或的等比例图片。',
			'attr'=>'mix bgs thumb other',
			'sort'=>22,
		),
		
		array(
			'tpltypeid'=>23,
			'tplview'=>'cate123.png',
			'tpltypename'=>'123_index_jge4s',
			'tpldesinfo'=>'汽车行业专属模板，顶部幻灯片建议尺寸为宽640*高320或近似等比例的图片，幻灯下4个图标为分类管理的前4个分类，后面分类依次展示，图片建议尺寸为宽302*高233或等比例图片，logo图标为官网logo，需等比尺寸的png格式图片。',
			'attr'=>'mix focu bgs other',
			'sort'=>23,
		),
		
		array(
			'tpltypeid'=>24,
			'tplview'=>'cate124.png',
			'tpltypename'=>'124_index_ghe5s',
			'tpldesinfo'=>'此模板适合做简单版纯展示的会员卡，头部图片就是首页封面图，宽720高随便，如果用幻灯片记住一定要相同的尺寸。小图标尺寸是正方形300x300,一个分类一页显示8个二级分类。',
			'attr'=>'mix sub focu bgs thumb other',
			'sort'=>24,
		),
		
		array(
			'tpltypeid'=>25,
			'tplview'=>'cate125.png',
			'tpltypename'=>'125_index_gjnh4',
			'tpldesinfo'=>'左右双栏模版，顶部幻灯片尺寸为640*320或近似等比例图片，如使用正方形图片会使得页面不美观；分类图片建议使用300*200或近似等比例图片，使用宽度小于高度的(如200*300)尺寸图片将使页面惨不忍睹。',
			'attr'=>'mix bgs focu thumb other',
			'sort'=>25,
		),
		
		array(
			'tpltypeid'=>26,
			'tplview'=>'cate126.png',
			'tpltypename'=>'126_index_gjj0f',
			'tpldesinfo'=>'图标式模版，顶部幻灯片建议使用尺寸为640*320或近似等比例图片；分类图片请使用正方形尺寸的图片。',
			'attr'=>'mix focu thumb bgs other',
			'sort'=>26,
		),
		
		array(
			'tpltypeid'=>27,
			'tplview'=>'cate127.png',
			'tpltypename'=>'127_index_jpr4g',
			'tpldesinfo'=>'',
			'attr'=>'mix focu bgs thumb other',
			'sort'=>27,
		),
		
		array(
			'tpltypeid'=>28,
			'tplview'=>'cate128.png',
			'tpltypename'=>'128_index_pgj3f',
			'tpldesinfo'=>'图标式模版，顶部幻灯片建议使用尺寸为640*320或近似等比例图片；分类图片请使用正方形尺寸的图片。',
			'attr'=>'mix focu bgs thumb other',
			'sort'=>28,
		),
		
		array(
			'tpltypeid'=>29,
			'tplview'=>'cate129.png',
			'tpltypename'=>'129_index_fds3f',
			'tpldesinfo'=>'图标式模版，顶部幻灯片建议使用尺寸为640*320或近似等比例图片；分类图片请使用正方形尺寸的图片。',
			'attr'=>'mix focu bgs thumb other',
			'sort'=>29,
		),
		
		array(
			'tpltypeid'=>30,
			'tplview'=>'cate130.png',
			'tpltypename'=>'130_index_ves7g',
			'tpldesinfo'=>'图标式模版，顶部幻灯片建议使用尺寸为640*320或近似等比例图片；分类图片请使用正方形尺寸的图片。',
			'attr'=>'mix focu bgs thumb other',
			'sort'=>30,
		),

		array(
			'tpltypeid'=>31,
			'tplview'=>'cate131.png',
			'tpltypename'=>'131_index_win6a',
			'tpldesinfo'=>'此模板适合做简单版纯展示的会员卡，头部图片就是首页封面图，宽720高随便，如果用幻灯片记住一定要相同的尺寸。小图标尺寸是正方形300x300,一个分类一页显示8个二级分类。',
			'attr'=>'mix sub focu bgs thumb other',
			'sort'=>31,
		),
		
		array(
			'tpltypeid'=>32,
			'tplview'=>'cate132.png',
			'tpltypename'=>'132_index_wio1a',
			'tpldesinfo'=>'此模板适合做简单版纯展示的会员卡，头部图片就是首页封面图，宽720高随便，如果用幻灯片记住一定要相同的尺寸。小图标尺寸是正方形300x300,一个分类一页显示6个二级分类。',
			'attr'=>'mix sub focu bgs thumb other',
			'sort'=>32,
		),
		
		array(
			'tpltypeid'=>33,
			'tplview'=>'cate133.png',
			'tpltypename'=>'133_index_wis2a',
			'tpldesinfo'=>'此模板支持二级分类，适合分类比较多的地方公众号，小图标为正方形300x300px。',
			'attr'=>'mix sub focu bgs thumb other',
			'sort'=>33,
		),
		
		array(
			'tpltypeid'=>34,
			'tplview'=>'cate134.png',
			'tpltypename'=>'134_index_viw3a',
			'tpldesinfo'=>'此模板支持二级分类，适合分类比较多的地方公众号，小图标为正方形300x300px。',
			'attr'=>'mix sub focu bgs thumb other',
			'sort'=>34,
		),
		
		array(
			'tpltypeid'=>35,
			'tplview'=>'cate135.png',
			'tpltypename'=>'135_index_you4a',
			'tpldesinfo'=>'此模板支持二级分类，适合分类比较多的地方公众号，前4个一级分类可以突出显示，小图标',
			'attr'=>'mix focu bgs thumb other',
			'sort'=>35,
		),		
		array(
			'tpltypeid'=>36,
			'tplview'=>'cate136.png',
			'tpltypename'=>'136_index_esfsd344',
			'tpldesinfo'=>'',
			'attr'=>'mix thumb bg bgs filt estate',
			'sort'=>36,
		),
		array(
			'tpltypeid'=>37,
			'tplview'=>'list1.png',
			'tpltypename'=>'yl_list',
			'tpldesinfo'=>'',
			'attr'=>'mix lis',
			'sort'=>37,
		),
		array(
			'tpltypeid'=>38,
			'tplview'=>'list4.png',
			'tpltypename'=>'ktv_list',
			'tpldesinfo'=>'',
			'attr'=>'mix lis',
			'sort'=>38,
		),
		array(
			'tpltypeid'=>39,
			'tplview'=>'cate139.png',
			'tpltypename'=>'139_index_ktv',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix focu thumb filt other',
			'sort'=>39,
		),
		array(
			'tpltypeid'=>40,
			'tplview'=>'cate140.png',
			'tpltypename'=>'140_index_qesf',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix focu thumb bgs other',
			'sort'=>40,
		),
		array(
			'tpltypeid'=>41,
			'tplview'=>'cate141.png',
			'tpltypename'=>'141_index_654d',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix focu thumb bgs other',
			'sort'=>41,
		),
		array(
			'tpltypeid'=>42,
			'tplview'=>'cate142.png',
			'tpltypename'=>'142_index_6uid',
			'tpldesinfo'=>'无头部幻灯片，小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs filt bg thumb estate',
			'sort'=>42,
		),
		array(
			'tpltypeid'=>43,
			'tplview'=>'cate143.png',
			'tpltypename'=>'143_index_53sd',
			'tpldesinfo'=>'无头部幻灯片，小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs filt bg thumb estate',
			'sort'=>43,
		),
		array(
			'tpltypeid'=>44,
			'tplview'=>'cate144.png',
			'tpltypename'=>'144_index_bfst',
			'tpldesinfo'=>'无头部幻灯片，小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs bg thumb other',
			'sort'=>44,
		),
		array(
			'tpltypeid'=>45,
			'tplview'=>'cate145.png',
			'tpltypename'=>'145_index_vbws',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu edu',
			'sort'=>45,
		),
		array(
			'tpltypeid'=>46,
			'tplview'=>'cate146.png',
			'tpltypename'=>'146_index_58sv',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>46,
		),
		array(
			'tpltypeid'=>47,
			'tplview'=>'cate147.png',
			'tpltypename'=>'147_index_verm',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>47,
		),
		array(
			'tpltypeid'=>48,
			'tplview'=>'cate148.png',
			'tpltypename'=>'148_index_bleu',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>48,
		),
		array(
			'tpltypeid'=>49,
			'tplview'=>'cate149.png',
			'tpltypename'=>'149_index_28ad',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>49,
		),
		array(
			'tpltypeid'=>50,
			'tplview'=>'cate150.png',
			'tpltypename'=>'150_index_28sv',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>50,
		),
		array(
			'tpltypeid'=>51,
			'tplview'=>'cate151.png',
			'tpltypename'=>'151_index_ve4y',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>51,
		),
		array(
			'tpltypeid'=>52,
			'tplview'=>'cate152.png',
			'tpltypename'=>'152_index_v82x',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>52,
		),
		array(
			'tpltypeid'=>53,
			'tplview'=>'cate153.png',
			'tpltypename'=>'153_index_58sdf',
			'tpldesinfo'=>'诺基亚X风格，披着wp外衣的android，不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>53,
		),
		array(
			'tpltypeid'=>54,
			'tplview'=>'cate154.png',
			'tpltypename'=>'154_index_f78d1',
			'tpldesinfo'=>'诺基亚X风格2，不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>54,
		),
		array(
			'tpltypeid'=>55,
			'tplview'=>'cate155.png',
			'tpltypename'=>'155_index_xym7',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>55,
		),
		array(
			'tpltypeid'=>56,
			'tplview'=>'cate156.png',
			'tpltypename'=>'156_index_64ay',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>56,
		),
		array(
			'tpltypeid'=>57,
			'tplview'=>'cate157.png',
			'tpltypename'=>'157_index_dgeh7',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>57,
		),
		array(
			'tpltypeid'=>58,
			'tplview'=>'cate158.png',
			'tpltypename'=>'158_index_ffy4',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>58,
		),
		array(
			'tpltypeid'=>59,
			'tplview'=>'cate159.png',
			'tpltypename'=>'159_index_fgft',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>59,
		),
		array(
			'tpltypeid'=>60,
			'tplview'=>'cate160.png',
			'tpltypename'=>'160_index_674f',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>60,
		),
		array(
			'tpltypeid'=>61,
			'tplview'=>'cate161.png',
			'tpltypename'=>'161_index_df3t',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>61,
		),
		array(
			'tpltypeid'=>62,
			'tplview'=>'cate162.png',
			'tpltypename'=>'162_index_xffe',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>62,
		),
		array(
			'tpltypeid'=>63,
			'tplview'=>'cate163.png',
			'tpltypename'=>'163_index_cve3',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>63,
		),
		array(
			'tpltypeid'=>64,
			'tplview'=>'cate164.png',
			'tpltypename'=>'164_index_5366',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu filt lis other',
			'sort'=>64,
		),
		array(
			'tpltypeid'=>65,
			'tplview'=>'cate165.png',
			'tpltypename'=>'165_index_6dgbf',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>65,
		),
		array(
			'tpltypeid'=>66,
			'tplview'=>'cate166.png',
			'tpltypename'=>'166_index_6dgbf',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>66,
		),
		array(
			'tpltypeid'=>67,
			'tplview'=>'cate167.png',
			'tpltypename'=>'167_index_6dgbf',
			'tpldesinfo'=>'小图标为正方形300x300px，图片建议360x200px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>67,
		),
		array(
			'tpltypeid'=>68,
			'tplview'=>'cate168.png',
			'tpltypename'=>'168_index_6dgbf',
			'tpldesinfo'=>'小图标为正方形300x300px，图片建议360x200px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>68,
		),
		array(
			'tpltypeid'=>69,
			'tplview'=>'cate169.png',
			'tpltypename'=>'169_index_6dgbf',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>69,
		),
		array(
			'tpltypeid'=>70,
			'tplview'=>'cate170.png',
			'tpltypename'=>'170_index_6dgbf',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>70,
		),
		array(
			'tpltypeid'=>71,
			'tplview'=>'cate171.png',
			'tpltypename'=>'171_index_stbn',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>71,
		),
		array(
			'tpltypeid'=>72,
			'tplview'=>'cate172.png',
			'tpltypename'=>'172_index_44g3',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>72,
		),
		array(
			'tpltypeid'=>73,
			'tplview'=>'cate173.png',
			'tpltypename'=>'173_index_6dff',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>73,
		),
		array(
			'tpltypeid'=>74,
			'tplview'=>'cate174.png',
			'tpltypename'=>'174_index_gh46',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>74,
		),
		array(
			'tpltypeid'=>75,
			'tplview'=>'cate175.png',
			'tpltypename'=>'175_index_6deh',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>75,
		),
		array(
			'tpltypeid'=>76,
			'tplview'=>'cate176.png',
			'tpltypename'=>'176_index_sda3',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>76,
		),
		array(
			'tpltypeid'=>77,
			'tplview'=>'cate177.png',
			'tpltypename'=>'177_index_gh5f',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>77,
		),
		array(
			'tpltypeid'=>78,
			'tplview'=>'cate178.png',
			'tpltypename'=>'178_index_shfr',
			'tpldesinfo'=>'不支持更换颜色风格',
			'attr'=>'mix bgs focu lis other',
			'sort'=>78,
		),
		array(
			'tpltypeid'=>79,
			'tplview'=>'cate179.png',
			'tpltypename'=>'179_index_4g4f',
			'tpldesinfo'=>'不支持更换颜色风格',
			'attr'=>'mix bgs focu lis other',
			'sort'=>79,
		),
		array(
			'tpltypeid'=>80,
			'tplview'=>'cate180.png',
			'tpltypename'=>'180_index_zfg4',
			'tpldesinfo'=>'不支持更换颜色风格',
			'attr'=>'mix bgs focu lis other',
			'sort'=>80,
		),
		array(
			'tpltypeid'=>81,
			'tplview'=>'cate181.png',
			'tpltypename'=>'181_index_dfg3',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>81,
		),
		array(
			'tpltypeid'=>82,
			'tplview'=>'cate182.png',
			'tpltypename'=>'182_index_sd3v',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>82,
		),
		array(
			'tpltypeid'=>83,
			'tplview'=>'cate183.png',
			'tpltypename'=>'183_index_zdfe',
			'tpldesinfo'=>'图片高度100，宽度不小于360px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu hotel beauty',
			'sort'=>83,
		),
		array(
			'tpltypeid'=>84,
			'tplview'=>'cate184.png',
			'tpltypename'=>'184_index_sdf3',
			'tpldesinfo'=>'图片高度100，宽度不小于360px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu hotel beauty',
			'sort'=>84,
		),
		array(
			'tpltypeid'=>85,
			'tplview'=>'cate185.png',
			'tpltypename'=>'185_index_gjerf',
			'tpldesinfo'=>'图片高度75，宽度不小于360px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu hotel beauty',
			'sort'=>85,
		),
		array(
			'tpltypeid'=>86,
			'tplview'=>'cate186.png',
			'tpltypename'=>'186_index_aasd',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu car',
			'sort'=>86,
		),
		array(
			'tpltypeid'=>87,
			'tplview'=>'cate187.png',
			'tpltypename'=>'187_index_4d8fw',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu car',
			'sort'=>87,
		),
		array(
			'tpltypeid'=>88,
			'tplview'=>'cate188.png',
			'tpltypename'=>'188_index_gcbr5',
			'tpldesinfo'=>'图标为正方形300x300px，图片建议360x200px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu car',
			'sort'=>88,
		),
		array(
			'tpltypeid'=>89,
			'tplview'=>'cate189.png',
			'tpltypename'=>'189_index_xcv2',
			'tpldesinfo'=>'图标为正方形300x300px，图片建议360x200px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu car',
			'sort'=>89,
		),
		array(
			'tpltypeid'=>90,
			'tplview'=>'cate190.png',
			'tpltypename'=>'190_index_xj643',
			'tpldesinfo'=>'不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>90,
		),
		array(
			'tpltypeid'=>91,
			'tplview'=>'cate191.png',
			'tpltypename'=>'191_index_zedv',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>91,
		),
		array(
			'tpltypeid'=>92,
			'tplview'=>'cate192.png',
			'tpltypename'=>'192_index_vbrn',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>92,
		),
		array(
			'tpltypeid'=>93,
			'tplview'=>'cate193.png',
			'tpltypename'=>'193_index_b4bt',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>93,
		),
		array(
			'tpltypeid'=>94,
			'tplview'=>'cate194.png',
			'tpltypename'=>'194_index_sc23',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>94,
		),
		array(
			'tpltypeid'=>95,
			'tplview'=>'cate195.png',
			'tpltypename'=>'195_index_xrb54',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>95,
		),
		array(
			'tpltypeid'=>96,
			'tplview'=>'cate196.png',
			'tpltypename'=>'196_index_sdf3',
			'tpldesinfo'=>'图片要么都是正方形300x300px，要么都是360x200px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu health',
			'sort'=>96,
		),
		array(
			'tpltypeid'=>97,
			'tplview'=>'cate197.png',
			'tpltypename'=>'197_index_cvrj',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>97,
		),
		array(
			'tpltypeid'=>98,
			'tplview'=>'cate198.png',
			'tpltypename'=>'198_index_xcwh',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu wedding',
			'sort'=>98,
		),
		array(
			'tpltypeid'=>99,
			'tplview'=>'cate199.png',
			'tpltypename'=>'199_index_asdw',
			'tpldesinfo'=>'图标为正方形300x300px，图片高度90，宽度不小于360px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>99,
		),
		array(
			'tpltypeid'=>100,
			'tplview'=>'cate1100.png',
			'tpltypename'=>'1100_index_btj5',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu bg filt slip estate',
			'sort'=>100,
		),
		array(
			'tpltypeid'=>101,
			'tplview'=>'cate1101.png',
			'tpltypename'=>'1101_index_sd3h',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu bg filt slip estate',
			'sort'=>101,
		),
		array(
			'tpltypeid'=>102,
			'tplview'=>'cate1102.png',
			'tpltypename'=>'1102_index_cvb5u',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix lis thumb other',
			'sort'=>102,
		),



		array(
			'tpltypeid'=>103,
			'tplview'=>'cate1103.png',
			'tpltypename'=>'1103_index_xfe5',
			'tpldesinfo'=>'图标为正方形300x300px，图片建议360x200px。不支持更换颜色风格',
			'attr'=>'mix lis thumb other',
			'sort'=>119,
		),
		array(
			'tpltypeid'=>104,
			'tplview'=>'cate1104.png',
			'tpltypename'=>'1104_index_xcvhk',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix lis thumb other',
			'sort'=>120,
		),
		array(
			'tpltypeid'=>105,
			'tplview'=>'cate1105.png',
			'tpltypename'=>'1105_index_fxfg',
			'tpldesinfo'=>'图标为正方形300x300px，图片建议360x200px。不支持更换颜色风格',
			'attr'=>'mix lis thumb other',
			'sort'=>121,
		),
		array(
			'tpltypeid'=>106,
			'tplview'=>'cate1106.png',
			'tpltypename'=>'1106_index_fxfg',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix lis thumb other',
			'sort'=>122,
		),
		array(
			'tpltypeid'=>107,
			'tplview'=>'cate1107.png',
			'tpltypename'=>'1107_index_fxfg',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix lis thumb other',
			'sort'=>123,
		),
		array(
			'tpltypeid'=>108,
			'tplview'=>'cate1108.png',
			'tpltypename'=>'1108_index_fxfg',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix lis thumb other',
			'sort'=>124,
		),
		array(
			'tpltypeid'=>109,
			'tplview'=>'cate1109.png',
			'tpltypename'=>'1109_index_fxfg',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix lis thumb other',
			'sort'=>125,
		),
		array(
			'tpltypeid'=>110,
			'tplview'=>'cate1110.png',
			'tpltypename'=>'1110_index_fxfg',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix lis thumb other',
			'sort'=>126,
		),
		array(
			'tpltypeid'=>111,
			'tplview'=>'cate1111.png',
			'tpltypename'=>'1111_index_cveg',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix lis thumb other',
			'sort'=>127,
		),
		array(
			'tpltypeid'=>112,
			'tplview'=>'cate1112.png',
			'tpltypename'=>'1112_index_xghx',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix lis thumb other',
			'sort'=>128,
		),
		array(
			'tpltypeid'=>113,
			'tplview'=>'cate1113.png',
			'tpltypename'=>'1113_index_cxve',
			'tpldesinfo'=>'支持二级分类，并且一级分类和子分类支持左右滑屏显示。前8个一级分类可以突出显示，小图标为正方形300x300px，图片要么都是正方形300x300px，要么都是360x200px。不支持更换颜色风格',
			'attr'=>'mix lis thumb other',
			'sort'=>129,
		),
		array(
			'tpltypeid'=>114,
			'tplview'=>'cate1114.png',
			'tpltypename'=>'1114_index_vbtd',
			'tpldesinfo'=>'支持二级分类，并且一级分类和子分类支持左右滑屏显示。适合分类比较多的地方公众号，前4个一级分类可以突出显示，小图标为正方形300x300px，图片要么都是正方形300x300px，要么都是360x200px。不支持更换颜色风格',
			'attr'=>'mix lis thumb other',
			'sort'=>130,
		),
		array(
			'tpltypeid'=>115,
			'tplview'=>'cate1115.png',
			'tpltypename'=>'1115_index_v3yh',
			'tpldesinfo'=>'支持二级分类，并且一级分类和子分类支持左右滑屏显示。适合分类比较多的地方公众号，前4个一级分类可以突出显示，小图标为正方形300x300px；图片要么都是正方形300x300px，要么都是360x200px。不支持更换颜色风格',
			'attr'=>'mix lis thumb other',
			'sort'=>131,
		),
		array(
			'tpltypeid'=>116,
			'tplview'=>'cate1116.png',
			'tpltypename'=>'1116_index_cv4y',
			'tpldesinfo'=>'支持二级分类，并且一级分类和子分类支持左右滑屏显示。适合分类比较多的地方公众号，前4个一级分类可以突出显示，图片要么都是正方形300x300px，要么都是360x200px。不支持更换颜色风格',
			'attr'=>'mix bg bgs filt lis other',
			'sort'=>132,
		),
		array(
			'tpltypeid'=>117,
			'tplview'=>'cate1117.png',
			'tpltypename'=>'1117_index_35y5',
			'tpldesinfo'=>'顶级最多显示6个分类，二级最多显示3个分类，不支持更换颜色风格',
			'attr'=>'mix sub bg other',
			'sort'=>117,
		),
		array(
			'tpltypeid'=>118,
			'tplview'=>'cate1118.png',
			'tpltypename'=>'1118_index_sdsc',
			'tpldesinfo'=>'可自定义背景轮播图，不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu bg filt slip estate',
			'sort'=>116,
		),
		array(
			'tpltypeid'=>119,
			'tplview'=>'cate1119.png',
			'tpltypename'=>'1119_index_asd52',
			'tpldesinfo'=>'适合在列表页使用，不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu restaurant',
			'sort'=>115,
		),
		array(
			'tpltypeid'=>120,
			'tplview'=>'cate1120.png',
			'tpltypename'=>'1120_index_ghg6',
			'tpldesinfo'=>'适合在列表页使用，不支持更换颜色风格',
			'attr'=>'mix bgs thumb filt bg other',
			'sort'=>114,
		),
		array(
			'tpltypeid'=>121,
			'tplview'=>'cate1121.png',
			'tpltypename'=>'1121_index_8sd55',
			'tpldesinfo'=>'适合在列表页使用，不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu hotel tour estate',
			'sort'=>113,
		),
		array(
			'tpltypeid'=>122,
			'tplview'=>'cate1122.png',
			'tpltypename'=>'1122_index_5sd2',
			'tpldesinfo'=>'适合在列表页使用，不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu other',
			'sort'=>112,
		),
		array(
			'tpltypeid'=>123,
			'tplview'=>'cate1123.png',
			'tpltypename'=>'1123_index_cvrn',
			'tpldesinfo'=>'适合在列表页使用，不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu slip other',
			'sort'=>111,
		),
		array(
			'tpltypeid'=>124,
			'tplview'=>'cate1124.png',
			'tpltypename'=>'1124_index_xegb',
			'tpldesinfo'=>'适合在列表页使用，不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu slip other',
			'sort'=>110,
		),
		array(
			'tpltypeid'=>125,
			'tplview'=>'cate1125.png',
			'tpltypename'=>'1125_index_xcvy',
			'tpldesinfo'=>'适合在列表页使用，不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu slip other',
			'sort'=>109,
		),
		array(
			'tpltypeid'=>126,
			'tplview'=>'cate1126.png',
			'tpltypename'=>'1126_index_85vvb',
			'tpldesinfo'=>'适合在列表页使用，不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu slip beauty',
			'sort'=>108,
		),
		array(
			'tpltypeid'=>127,
			'tplview'=>'cate1127.png',
			'tpltypename'=>'1127_index_klgh',
			'tpldesinfo'=>'适合在列表页使用，不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu slip hotel',
			'sort'=>107,
		),
		array(
			'tpltypeid'=>128,
			'tplview'=>'cate1128.png',
			'tpltypename'=>'1128_index_vner',
			'tpldesinfo'=>'适合在列表页使用，不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu slip other',
			'sort'=>106,
		),
		array(
			'tpltypeid'=>129,
			'tplview'=>'cate1129.png',
			'tpltypename'=>'1129_index_vner',
			'tpldesinfo'=>'适合在列表页使用，不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu sub slip restaurant',
			'sort'=>105,
		),
		array(
			'tpltypeid'=>130,
			'tplview'=>'cate1130.png',
			'tpltypename'=>'1130_index_85xc',
			'tpldesinfo'=>'适合在列表页使用，不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu sub slip restaurant',
			'sort'=>104,
		),
		array(
			'tpltypeid'=>131,
			'tplview'=>'cate1131.png',
			'tpltypename'=>'1131_index_nr34',
			'tpldesinfo'=>'适合在列表页使用，不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu sub slip restaurant',
			'sort'=>103,
		),
		array(
			'tpltypeid'=>132,
			'tplview'=>'cate1132.png',
			'tpltypename'=>'1132_index_mng5',
			'tpldesinfo'=>'适合在列表页使用，不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu sub slip tour',
			'sort'=>102,
		),
		array(
			'tpltypeid'=>133,
			'tplview'=>'cate1133.png',
			'tpltypename'=>'1133_index_rgcv',
			'tpldesinfo'=>'不支持更换颜色风格',
			'attr'=>'mix focu thumb bgs other',
			'sort'=>133,
		),
		array(
			'tpltypeid'=>134,
			'tplview'=>'cate1134.png',
			'tpltypename'=>'1134_index_cv4s',
			'tpldesinfo'=>'支持二级分类，并且一级分类和子分类支持左右滑屏显示。头部图片尺寸推荐360x45，中间的大图就是一级分类图片，尺寸推荐360x100，不支持更换颜色风格',
			'attr'=>'mix focu thumb bgs sub car',
			'sort'=>134,
		),
		array(
			'tpltypeid'=>135,
			'tplview'=>'cate1135.png',
			'tpltypename'=>'1135_index_xcev',
			'tpldesinfo'=>'支持二级分类，并且一级分类和子分类支持左右滑屏显示。头部图片尺寸推荐360x45，中间的大图就是一级分类图片，尺寸推荐360x100，二级分类图片尺寸推荐360x200px，不支持更换颜色风格',
			'attr'=>'mix focu thumb bgs sub car',
			'sort'=>135,
		),
		array(
			'tpltypeid'=>136,
			'tplview'=>'cate1136.png',
			'tpltypename'=>'1136_index_n4fb',
			'tpldesinfo'=>'windowsphone风格，无幻灯片。分类的图片为300x300正方形图片，记住一定要相同的尺寸，都是300x300。',
			'attr'=>'mix thumb other',
			'sort'=>136,
		),
		array(
			'tpltypeid'=>137,
			'tplview'=>'cate1137.png',
			'tpltypename'=>'146_index_4639',
			'tpldesinfo'=>'大气精美的酒店模板',
			'attr'=>'mix thumb filt bg bgs hotel tour estate',
			'sort'=>137,
		),
		array(
			'tpltypeid'=>138,
			'tplview'=>'cate1138.png',
			'tpltypename'=>'1138_index_n4fb',
			'tpldesinfo'=>'大气精美的酒店模板',
			'attr'=>'mix thumb filt bg bgs hotel tour estate',
			'sort'=>138,
		),
		array(
			'tpltypeid'=>139,
			'tplview'=>'cate1139.png',
			'tpltypename'=>'1139_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu slip hotel',
			'sort'=>139,
		),
		array(
			'tpltypeid'=>140,
			'tplview'=>'cate1140.png',
			'tpltypename'=>'1140_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu slip hotel',
			'sort'=>140,
		),
		array(
			'tpltypeid'=>141,
			'tplview'=>'cate1141.png',
			'tpltypename'=>'1141_index_n4fb',
			'tpldesinfo'=>'左右图文式模版，顶部幻灯片建议使用尺寸为640*320或近似等比例图片；分类图片建议使用450*300或近似等比例图片，请不要使用高度大于或接近于宽度的图片',
			'attr'=>'mix hotel tour bgs focu thumb',
			'sort'=>141,
		),
		array(
			'tpltypeid'=>142,
			'tplview'=>'cate1142.png',
			'tpltypename'=>'1142_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb filt bg hotel',
			'sort'=>142,
		),
		array(
			'tpltypeid'=>143,
			'tplview'=>'cate1143.png',
			'tpltypename'=>'1143_index_n4fb',
			'tpldesinfo'=>'大气精美的酒店模板',
			'attr'=>'mix hotel tour bgs bg filt',
			'sort'=>143,
		),
		array(
			'tpltypeid'=>144,
			'tplview'=>'cate1144.png',
			'tpltypename'=>'1144_index_n4fb',
			'tpldesinfo'=>'大气精美的酒店模板',
			'attr'=>'mix bg bgs filt hotel tour',
			'sort'=>144,
		),
		array(
			'tpltypeid'=>145,
			'tplview'=>'cate1145.png',
			'tpltypename'=>'1145_index_n4fb',
			'tpldesinfo'=>'大气精美的酒店模板',
			'attr'=>'mix hotel tour thumb focu bgs',
			'sort'=>145,
		),
		array(
			'tpltypeid'=>146,
			'tplview'=>'cate1146.png',
			'tpltypename'=>'1146_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu hotel tour estate',
			'sort'=>146,
		),
		array(
			'tpltypeid'=>147,
			'tplview'=>'cate1147.png',
			'tpltypename'=>'1147_index_n4fb',
			'tpldesinfo'=>'图片要么都是正方形300x300px，要么都是360x200px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu hotel estate',
			'sort'=>147,
		),
		array(
			'tpltypeid'=>148,
			'tplview'=>'cate1148.png',
			'tpltypename'=>'1148_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu hotel',
			'sort'=>148,
		),
		array(
			'tpltypeid'=>149,
			'tplview'=>'cate1149.png',
			'tpltypename'=>'1149_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu hotel tour',
			'sort'=>149,
		),
		array(
			'tpltypeid'=>150,
			'tplview'=>'cate1150.png',
			'tpltypename'=>'1150_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu hotel tour',
			'sort'=>150,
		),
		array(
			'tpltypeid'=>151,
			'tplview'=>'cate1151.png',
			'tpltypename'=>'1151_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu hotel estate',
			'sort'=>151,
		),
		array(
			'tpltypeid'=>152,
			'tplview'=>'cate1152.png',
			'tpltypename'=>'1152_index_n4fb',
			'tpldesinfo'=>'大气精美的汽车行业模板',
			'attr'=>'mix car bgs bg filt',
			'sort'=>152,
		),
		array(
			'tpltypeid'=>153,
			'tplview'=>'cate1153.png',
			'tpltypename'=>'1153_index_n4fb',
			'tpldesinfo'=>'大气精美的汽车行业模板',
			'attr'=>'mix bgs focu lis car',
			'sort'=>153,
		),
		array(
			'tpltypeid'=>154,
			'tplview'=>'cate1154.png',
			'tpltypename'=>'1154_index_n4fb',
			'tpldesinfo'=>'大气精美的汽车行业模板',
			'attr'=>'mix focu thumb bgs car',
			'sort'=>154,
		),
		array(
			'tpltypeid'=>155,
			'tplview'=>'cate1155.png',
			'tpltypename'=>'1155_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb filt bg car',
			'sort'=>155,
		),
		array(
			'tpltypeid'=>156,
			'tplview'=>'cate1156.png',
			'tpltypename'=>'1156_index_n4fb',
			'tpldesinfo'=>'汽车行业专属模板，顶部幻灯片建议尺寸为宽640*高320或近似等比例的图片，幻灯下4个图标为分类管理的前4个分类，后面分类依次展示，图片建议尺寸为宽302*高233或等比例图片，logo图标为官网logo，需等比尺寸的png格式图片',
			'attr'=>'mix focu bgs car',
			'sort'=>156,
		),
		array(
			'tpltypeid'=>157,
			'tplview'=>'cate1157.png',
			'tpltypename'=>'1157_index_n4fb',
			'tpldesinfo'=>'大气精美的汽车行业模板',
			'attr'=>'mix bgs focu lis car',
			'sort'=>157,
		),
		array(
			'tpltypeid'=>158,
			'tplview'=>'cate1158.png',
			'tpltypename'=>'1158_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu slip car',
			'sort'=>158,
		),
		array(
			'tpltypeid'=>159,
			'tplview'=>'cate1159.png',
			'tpltypename'=>'1159_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu slip car',
			'sort'=>159,
		),
		array(
			'tpltypeid'=>160,
			'tplview'=>'cate1160.png',
			'tpltypename'=>'1160_index_n4fb',
			'tpldesinfo'=>'大气精美的汽车行业模板',
			'attr'=>'mix bgs focu lis car',
			'sort'=>160,
		),
		array(
			'tpltypeid'=>161,
			'tplview'=>'cate1161.png',
			'tpltypename'=>'1161_index_n4fb',
			'tpldesinfo'=>'大气精美的汽车行业模板',
			'attr'=>'mix thumb bg bgs filt car',
			'sort'=>161,
		),
		array(
			'tpltypeid'=>162,
			'tplview'=>'cate1162.png',
			'tpltypename'=>'1162_index_n4fb',
			'tpldesinfo'=>'左右图文式模版，顶部幻灯片建议使用尺寸为640*320或近似等比例图片；分类图片建议使用450*300或近似等比例图片，请不要使用高度大于或接近于宽度的图片',
			'attr'=>'mix car bgs focu thumb',
			'sort'=>162,
		),
		array(
			'tpltypeid'=>163,
			'tplview'=>'cate1163.png',
			'tpltypename'=>'1163_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu filt lis tour',
			'sort'=>163,
		),
		array(
			'tpltypeid'=>164,
			'tplview'=>'cate1164.png',
			'tpltypename'=>'1164_index_n4fb',
			'tpldesinfo'=>'大气精美的旅游行业模板',
			'attr'=>'mix thumb filt bg bgs tour',
			'sort'=>164,
		),
		array(
			'tpltypeid'=>165,
			'tplview'=>'cate1165.png',
			'tpltypename'=>'1165_index_n4fb',
			'tpldesinfo'=>'图标式模板，顶部幻灯片建议尺寸为宽640*高320或近似等比例的图片，分类前8个为图标及文字展示，后面分类为图片展示，建议尺寸为宽150*高90或等比例图片',
			'attr'=>'mix focu bgs thumb tour',
			'sort'=>165,
		),
		array(
			'tpltypeid'=>166,
			'tplview'=>'cate1166.png',
			'tpltypename'=>'1166_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu tour estate',
			'sort'=>166,
		),
		array(
			'tpltypeid'=>167,
			'tplview'=>'cate1167.png',
			'tpltypename'=>'1167_index_n4fb',
			'tpldesinfo'=>'大气精美的旅游行业模板',
			'attr'=>'mix thumb bg bgs filt tour',
			'sort'=>167,
		),
		array(
			'tpltypeid'=>168,
			'tplview'=>'cate1168.png',
			'tpltypename'=>'1168_index_n4fb',
			'tpldesinfo'=>'大气精美的旅游行业模板',
			'attr'=>'mix bg bgs filt tour estate',
			'sort'=>168,
		),
		array(
			'tpltypeid'=>169,
			'tplview'=>'cate1169.png',
			'tpltypename'=>'1169_index_n4fb',
			'tpldesinfo'=>'大气精美的旅游行业模板',
			'attr'=>'mix tour thumb focu bgs',
			'sort'=>169,
		),
		array(
			'tpltypeid'=>170,
			'tplview'=>'cate1170.png',
			'tpltypename'=>'1170_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px，图片建议360x200px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu tour',
			'sort'=>170,
		),
		array(
			'tpltypeid'=>171,
			'tplview'=>'cate1171.png',
			'tpltypename'=>'1171_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px，图片建议360x200px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu tour',
			'sort'=>171,
		),
		array(
			'tpltypeid'=>172,
			'tplview'=>'cate1172.png',
			'tpltypename'=>'1172_index_n4fb',
			'tpldesinfo'=>'大气精美的旅游行业模板',
			'attr'=>'mix bgs focu lis tour',
			'sort'=>172,
		),
		array(
			'tpltypeid'=>173,
			'tplview'=>'cate1173.png',
			'tpltypename'=>'1173_index_n4fb',
			'tpldesinfo'=>'大气精美的旅游行业模板',
			'attr'=>'mix bgs focu lis tour',
			'sort'=>173,
		),
		array(
			'tpltypeid'=>174,
			'tplview'=>'cate1174.png',
			'tpltypename'=>'1174_index_n4fb',
			'tpldesinfo'=>'图标式模板，顶部幻灯片建议尺寸为宽640*高320或近似等比例的图片，分类前8个为图标及文字展示，后面分类为图片展示，建议尺寸为宽150*高90或等比例图片',
			'attr'=>'mix focu bgs thumb restaurant',
			'sort'=>174,
		),
		array(
			'tpltypeid'=>175,
			'tplview'=>'cate1175.png',
			'tpltypename'=>'1175_index_n4fb',
			'tpldesinfo'=>'大气精美的餐饮行业模板',
			'attr'=>'mix focu thumb bgs restaurant',
			'sort'=>175,
		),
		array(
			'tpltypeid'=>176,
			'tplview'=>'cate1176.png',
			'tpltypename'=>'1176_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu slip restaurant',
			'sort'=>176,
		),
		array(
			'tpltypeid'=>177,
			'tplview'=>'cate1177.png',
			'tpltypename'=>'1177_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu slip restaurant',
			'sort'=>177,
		),
		array(
			'tpltypeid'=>178,
			'tplview'=>'cate1178.png',
			'tpltypename'=>'1178_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu slip restaurant',
			'sort'=>178,
		),
		array(
			'tpltypeid'=>179,
			'tplview'=>'cate1179.png',
			'tpltypename'=>'1179_index_n4fb',
			'tpldesinfo'=>'图标为正方形300x300px，图片建议360x200px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu restaurant',
			'sort'=>179,
		),
		array(
			'tpltypeid'=>180,
			'tplview'=>'cate1180.png',
			'tpltypename'=>'1180_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb filt bg restaurant',
			'sort'=>180,
		),
		array(
			'tpltypeid'=>181,
			'tplview'=>'cate1181.png',
			'tpltypename'=>'1181_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu restaurant',
			'sort'=>181,
		),
		array(
			'tpltypeid'=>182,
			'tplview'=>'cate1182.png',
			'tpltypename'=>'1182_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu restaurant',
			'sort'=>182,
		),
		array(
			'tpltypeid'=>183,
			'tplview'=>'cate1183.png',
			'tpltypename'=>'1183_index_n4fb',
			'tpldesinfo'=>'大气精美的餐饮行业模板',
			'attr'=>'mix thumb filt bg bgs restaurant',
			'sort'=>183,
		),
		array(
			'tpltypeid'=>184,
			'tplview'=>'cate1184.png',
			'tpltypename'=>'1184_index_n4fb',
			'tpldesinfo'=>'大气精美的餐饮行业模板',
			'attr'=>'mix thumb filt bg bgs restaurant',
			'sort'=>184,
		),
		array(
			'tpltypeid'=>185,
			'tplview'=>'cate1185.png',
			'tpltypename'=>'1185_index_n4fb',
			'tpldesinfo'=>'大气精美的餐饮行业模板',
			'attr'=>'mix bg bgs filt restaurant',
			'sort'=>185,
		),
		array(
			'tpltypeid'=>186,
			'tplview'=>'cate1186.png',
			'tpltypename'=>'1186_index_n4fb',
			'tpldesinfo'=>'大气精美的餐饮行业模板',
			'attr'=>'mix restaurant bgs bg filt',
			'sort'=>186,
		),
		array(
			'tpltypeid'=>187,
			'tplview'=>'cate1187.png',
			'tpltypename'=>'1187_index_n4fb',
			'tpldesinfo'=>'左右图文式模版，顶部幻灯片建议使用尺寸为640*320或近似等比例图片；分类图片建议使用450*300或近似等比例图片，请不要使用高度大于或接近于宽度的图片',
			'attr'=>'mix restaurant bgs focu thumb',
			'sort'=>187,
		),
		array(
			'tpltypeid'=>188,
			'tplview'=>'cate1188.png',
			'tpltypename'=>'1188_index_n4fb',
			'tpldesinfo'=>'左右图文式模版，顶部幻灯片建议使用尺寸为640*320或近似等比例图片；分类图片建议使用450*300或近似等比例图片，请不要使用高度大于或接近于宽度的图片',
			'attr'=>'mix restaurant bgs focu thumb',
			'sort'=>188,
		),
		array(
			'tpltypeid'=>189,
			'tplview'=>'cate1189.png',
			'tpltypename'=>'1189_index_n4fb',
			'tpldesinfo'=>'大气精美的餐饮行业模板',
			'attr'=>'mix restaurant thumb focu bgs',
			'sort'=>189,
		),
		array(
			'tpltypeid'=>190,
			'tplview'=>'cate1190.png',
			'tpltypename'=>'1190_index_n4fb',
			'tpldesinfo'=>'大气精美的餐饮行业模板',
			'attr'=>'mix focu thumb bgs restaurant',
			'sort'=>190,
		),
		array(
			'tpltypeid'=>191,
			'tplview'=>'cate1191.png',
			'tpltypename'=>'1191_index_n4fb',
			'tpldesinfo'=>'大气精美的房地产行业模板',
			'attr'=>'mix focu thumb bgs estate',
			'sort'=>191,
		),
		array(
			'tpltypeid'=>192,
			'tplview'=>'cate1192.png',
			'tpltypename'=>'1192_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu estate',
			'sort'=>192,
		),
		array(
			'tpltypeid'=>193,
			'tplview'=>'cate1193.png',
			'tpltypename'=>'1193_index_n4fb',
			'tpldesinfo'=>'大气精美的房地产行业模板',
			'attr'=>'mix bgs focu lis beauty',
			'sort'=>193,
		),
		array(
			'tpltypeid'=>194,
			'tplview'=>'cate1194.png',
			'tpltypename'=>'1194_index_n4fb',
			'tpldesinfo'=>'大气精美的房地产行业模板',
			'attr'=>'mix bgs focu lis estate',
			'sort'=>194,
		),
		array(
			'tpltypeid'=>195,
			'tplview'=>'cate1195.png',
			'tpltypename'=>'1195_index_n4fb',
			'tpldesinfo'=>'大气精美的房地产行业模板',
			'attr'=>'mix bgs focu lis estate',
			'sort'=>195,
		),
		array(
			'tpltypeid'=>196,
			'tplview'=>'cate1196.png',
			'tpltypename'=>'1196_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu estate',
			'sort'=>196,
		),
		array(
			'tpltypeid'=>197,
			'tplview'=>'cate1197.png',
			'tpltypename'=>'1197_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu filt lis estate',
			'sort'=>197,
		),
		array(
			'tpltypeid'=>198,
			'tplview'=>'cate1198.png',
			'tpltypename'=>'1198_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu estate',
			'sort'=>198,
		),
		array(
			'tpltypeid'=>199,
			'tplview'=>'cate1199.png',
			'tpltypename'=>'1199_index_n4fb',
			'tpldesinfo'=>'大气精美的房地产行业模板',
			'attr'=>'mix thumb bg bgs filt estate',
			'sort'=>199,
		),
		array(
			'tpltypeid'=>200,
			'tplview'=>'cate1200.png',
			'tpltypename'=>'1200_index_n4fb',
			'tpldesinfo'=>'大气精美的房地产行业模板',
			'attr'=>'mix estate bgs bg filt',
			'sort'=>200,
		),
		array(
			'tpltypeid'=>201,
			'tplview'=>'cate1201.png',
			'tpltypename'=>'1201_index_n4fb',
			'tpldesinfo'=>'大气精美的医疗保健行业模板',
			'attr'=>'mix bgs thumb focu health',
			'sort'=>201,
		),
		array(
			'tpltypeid'=>202,
			'tplview'=>'cate1202.png',
			'tpltypename'=>'1202_index_n4fb',
			'tpldesinfo'=>'大气精美的医疗保健行业模板',
			'attr'=>'mix bgs focu lis health',
			'sort'=>202,
		),
		array(
			'tpltypeid'=>203,
			'tplview'=>'cate1203.png',
			'tpltypename'=>'1203_index_n4fb',
			'tpldesinfo'=>'大气精美的医疗保健行业模板',
			'attr'=>'mix bgs focu lis health',
			'sort'=>203,
		),
		array(
			'tpltypeid'=>204,
			'tplview'=>'cate1204.png',
			'tpltypename'=>'1204_index_n4fb',
			'tpldesinfo'=>'大气精美的医疗保健行业模板',
			'attr'=>'mix bgs thumb focu health',
			'sort'=>204,
		),
		array(
			'tpltypeid'=>205,
			'tplview'=>'cate1205.png',
			'tpltypename'=>'1205_index_n4fb',
			'tpldesinfo'=>'大气精美的医疗保健行业模板',
			'attr'=>'mix bgs thumb focu health',
			'sort'=>205,
		),
		array(
			'tpltypeid'=>206,
			'tplview'=>'cate1206.png',
			'tpltypename'=>'1206_index_n4fb',
			'tpldesinfo'=>'大气精美的医疗保健行业模板',
			'attr'=>'mix focu thumb bgs health',
			'sort'=>206,
		),
		array(
			'tpltypeid'=>207,
			'tplview'=>'cate1207.png',
			'tpltypename'=>'1207_index_n4fb',
			'tpldesinfo'=>'大气精美的医疗保健行业模板',
			'attr'=>'mix thumb filt bg bgs health',
			'sort'=>207,
		),
		array(
			'tpltypeid'=>208,
			'tplview'=>'cate1208.png',
			'tpltypename'=>'1208_index_n4fb',
			'tpldesinfo'=>'大气精美的医疗保健行业模板',
			'attr'=>'mix thumb filt bg bgs health',
			'sort'=>208,
		),
		array(
			'tpltypeid'=>209,
			'tplview'=>'cate1209.png',
			'tpltypename'=>'1209_index_n4fb',
			'tpldesinfo'=>'大气精美的医疗保健行业模板',
			'attr'=>'mix thumb filt bg bgs health',
			'sort'=>209,
		),
		array(
			'tpltypeid'=>210,
			'tplview'=>'cate1210.png',
			'tpltypename'=>'1210_index_n4fb',
			'tpldesinfo'=>'大气精美的医疗保健行业模板',
			'attr'=>'mix health bgs bg filt',
			'sort'=>210,
		),
		array(
			'tpltypeid'=>211,
			'tplview'=>'cate1211.png',
			'tpltypename'=>'1211_index_n4fb',
			'tpldesinfo'=>'大气精美的医疗保健行业模板',
			'attr'=>'mix bg bgs filt health',
			'sort'=>211,
		),
		array(
			'tpltypeid'=>212,
			'tplview'=>'cate1212.png',
			'tpltypename'=>'1212_index_n4fb',
			'tpldesinfo'=>'大气精美的医疗保健行业模板',
			'attr'=>'mix health bgs bg filt',
			'sort'=>212,
		),
		array(
			'tpltypeid'=>213,
			'tplview'=>'cate1213.png',
			'tpltypename'=>'1213_index_n4fb',
			'tpldesinfo'=>'大气精美的医疗保健行业模板',
			'attr'=>'mix bg bgs filt health',
			'sort'=>213,
		),
		array(
			'tpltypeid'=>214,
			'tplview'=>'cate1214.png',
			'tpltypename'=>'1214_index_n4fb',
			'tpldesinfo'=>'左右图文式模版，顶部幻灯片建议使用尺寸为640*320或近似等比例图片；分类图片建议使用450*300或近似等比例图片，请不要使用高度大于或接近于宽度的图片',
			'attr'=>'mix health bgs focu thumb',
			'sort'=>214,
		),
		array(
			'tpltypeid'=>215,
			'tplview'=>'cate1215.png',
			'tpltypename'=>'1215_index_n4fb',
			'tpldesinfo'=>'列表式图片模版，缩略图建议使用150*150或近似尺寸比例的图片',
			'attr'=>'mix health thumb focu bgs lis',
			'sort'=>215,
		),
		array(
			'tpltypeid'=>216,
			'tplview'=>'cate1216.png',
			'tpltypename'=>'1216_index_n4fb',
			'tpldesinfo'=>'大气精美的医疗保健行业模板',
			'attr'=>'mix focu thumb bgs health',
			'sort'=>216,
		),
		array(
			'tpltypeid'=>217,
			'tplview'=>'cate1217.png',
			'tpltypename'=>'1217_index_n4fb',
			'tpldesinfo'=>'图标式模板，顶部幻灯片建议尺寸为宽640*高320或近似等比例的图片，分类前8个为图标及文字展示，后面分类为图片展示，建议尺寸为宽150*高90或等比例图片',
			'attr'=>'mix focu bgs thumb edu',
			'sort'=>217,
		),
		array(
			'tpltypeid'=>218,
			'tplview'=>'cate1218.png',
			'tpltypename'=>'1218_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu slip beauty',
			'sort'=>218,
		),
		array(
			'tpltypeid'=>219,
			'tplview'=>'cate1219.png',
			'tpltypename'=>'1219_index_n4fb',
			'tpldesinfo'=>'图标为正方形300x300px，图片建议360x200px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu edu',
			'sort'=>219,
		),
		array(
			'tpltypeid'=>220,
			'tplview'=>'cate1220.png',
			'tpltypename'=>'1220_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu beauty',
			'sort'=>220,
		),
		array(
			'tpltypeid'=>221,
			'tplview'=>'cate1221.png',
			'tpltypename'=>'1221_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu beauty',
			'sort'=>221,
		),
		array(
			'tpltypeid'=>222,
			'tplview'=>'cate1222.png',
			'tpltypename'=>'1222_index_n4fb',
			'tpldesinfo'=>'图片要么都是正方形300x300px，要么都是360x200px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu beauty',
			'sort'=>222,
		),
		array(
			'tpltypeid'=>223,
			'tplview'=>'cate1223.png',
			'tpltypename'=>'1223_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu edu',
			'sort'=>223,
		),
		array(
			'tpltypeid'=>224,
			'tplview'=>'cate1224.png',
			'tpltypename'=>'1224_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu beauty',
			'sort'=>224,
		),
		array(
			'tpltypeid'=>225,
			'tplview'=>'cate1225.png',
			'tpltypename'=>'1225_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu beauty',
			'sort'=>225,
		),
		array(
			'tpltypeid'=>226,
			'tplview'=>'cate1226.png',
			'tpltypename'=>'1226_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu beauty',
			'sort'=>226,
		),
		array(
			'tpltypeid'=>227,
			'tplview'=>'cate1227.png',
			'tpltypename'=>'1227_index_n4fb',
			'tpldesinfo'=>'大气精美的教育行业模板',
			'attr'=>'mix beauty bgs thumb focu',
			'sort'=>227,
		),
		array(
			'tpltypeid'=>228,
			'tplview'=>'cate1228.png',
			'tpltypename'=>'1228_index_n4fb',
			'tpldesinfo'=>'大气精美的教育行业模板',
			'attr'=>'mix bgs thumb focu edu',
			'sort'=>228,
		),
		array(
			'tpltypeid'=>229,
			'tplview'=>'cate1229.png',
			'tpltypename'=>'1229_index_n4fb',
			'tpldesinfo'=>'大气精美的教育行业模板',
			'attr'=>'mix bgs thumb focu edu',
			'sort'=>229,
		),
		array(
			'tpltypeid'=>230,
			'tplview'=>'cate1230.png',
			'tpltypename'=>'1230_index_n4fb',
			'tpldesinfo'=>'大气精美的教育行业模板',
			'attr'=>'mix thumb bg bgs filt edu',
			'sort'=>230,
		),
		array(
			'tpltypeid'=>231,
			'tplview'=>'cate1231.png',
			'tpltypename'=>'1231_index_n4fb',
			'tpldesinfo'=>'大气精美的教育行业模板',
			'attr'=>'mix thumb filt bg bgs edu',
			'sort'=>231,
		),
		array(
			'tpltypeid'=>232,
			'tplview'=>'cate1232.png',
			'tpltypename'=>'1232_index_n4fb',
			'tpldesinfo'=>'大气精美的教育行业模板',
			'attr'=>'mix thumb filt bg bgs edu',
			'sort'=>232,
		),
		array(
			'tpltypeid'=>233,
			'tplview'=>'cate1233.png',
			'tpltypename'=>'1233_index_n4fb',
			'tpldesinfo'=>'大气精美的教育行业模板',
			'attr'=>'mix edu bgs bg filt',
			'sort'=>233,
		),
		array(
			'tpltypeid'=>234,
			'tplview'=>'cate1234.png',
			'tpltypename'=>'1234_index_n4fb',
			'tpldesinfo'=>'大气精美的教育行业模板',
			'attr'=>'mix bg bgs filt edu',
			'sort'=>234,
		),
		array(
			'tpltypeid'=>235,
			'tplview'=>'cate1235.png',
			'tpltypename'=>'1235_index_n4fb',
			'tpldesinfo'=>'大气精美的教育行业模板',
			'attr'=>'mix bg bgs filt edu',
			'sort'=>235,
		),
		array(
			'tpltypeid'=>236,
			'tplview'=>'cate1236.png',
			'tpltypename'=>'1236_index_n4fb',
			'tpldesinfo'=>'图标式模板，顶部幻灯片建议尺寸为宽640*高320或近似等比例的图片，分类前8个为图标及文字展示，后面分类为图片展示，建议尺寸为宽150*高90或等比例图片',
			'attr'=>'mix focu bgs thumb beauty',
			'sort'=>236,
		),
		array(
			'tpltypeid'=>237,
			'tplview'=>'cate1237.png',
			'tpltypename'=>'1237_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu slip beauty',
			'sort'=>237,
		),
		array(
			'tpltypeid'=>238,
			'tplview'=>'cate1238.png',
			'tpltypename'=>'1238_index_n4fb',
			'tpldesinfo'=>'大气精美的健身美容行业模板',
			'attr'=>'mix bgs focu lis beauty',
			'sort'=>238,
		),
		array(
			'tpltypeid'=>239,
			'tplview'=>'cate1239.png',
			'tpltypename'=>'1239_index_n4fb',
			'tpldesinfo'=>'图标式模板，顶部幻灯片建议尺寸为宽640*高320或近似等比例的图片，分类前8个为图标及文字展示，后面分类为图片展示，建议尺寸为宽150*高90或等比例图片',
			'attr'=>'mix focu bgs thumb wedding',
			'sort'=>239,
		),
		array(
			'tpltypeid'=>240,
			'tplview'=>'cate1240.png',
			'tpltypename'=>'1240_index_n4fb',
			'tpldesinfo'=>'大气精美的婚纱摄影行业模板',
			'attr'=>'mix focu thumb bgs wedding',
			'sort'=>240,
		),
		array(
			'tpltypeid'=>241,
			'tplview'=>'cate1241.png',
			'tpltypename'=>'1241_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu wedding',
			'sort'=>241,
		),
		array(
			'tpltypeid'=>242,
			'tplview'=>'cate1242.png',
			'tpltypename'=>'1242_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb filt bg wedding',
			'sort'=>242,
		),
		array(
			'tpltypeid'=>243,
			'tplview'=>'cate1243.png',
			'tpltypename'=>'1243_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu wedding',
			'sort'=>243,
		),
		array(
			'tpltypeid'=>244,
			'tplview'=>'cate1244.png',
			'tpltypename'=>'1244_index_n4fb',
			'tpldesinfo'=>'图片要么都是正方形300x300px，要么都是360x200px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu wedding',
			'sort'=>244,
		),
		array(
			'tpltypeid'=>245,
			'tplview'=>'cate1245.png',
			'tpltypename'=>'1245_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu wedding',
			'sort'=>245,
		),
		array(
			'tpltypeid'=>246,
			'tplview'=>'cate1246.png',
			'tpltypename'=>'1246_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu wedding',
			'sort'=>246,
		),
		array(
			'tpltypeid'=>247,
			'tplview'=>'cate1247.png',
			'tpltypename'=>'1247_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu wedding',
			'sort'=>247,
		),
		array(
			'tpltypeid'=>248,
			'tplview'=>'cate1248.png',
			'tpltypename'=>'1248_index_n4fb',
			'tpldesinfo'=>'大气精美的婚纱摄影行业模板',
			'attr'=>'mix wedding bgs thumb focu',
			'sort'=>248,
		),
		array(
			'tpltypeid'=>249,
			'tplview'=>'cate1249.png',
			'tpltypename'=>'1249_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu wedding',
			'sort'=>249,
		),
		array(
			'tpltypeid'=>250,
			'tplview'=>'cate1250.png',
			'tpltypename'=>'1250_index_n4fb',
			'tpldesinfo'=>'图片高度75，宽度不小于360px。不支持更换颜色风格',
			'attr'=>'mix bgs thumb focu wedding',
			'sort'=>250,
		),
		array(
			'tpltypeid'=>251,
			'tplview'=>'cate1251.png',
			'tpltypename'=>'1251_index_n4fb',
			'tpldesinfo'=>'大气精美的婚纱摄影行业模板',
			'attr'=>'mix thumb bg bgs filt wedding',
			'sort'=>251,
		),
		array(
			'tpltypeid'=>252,
			'tplview'=>'cate1252.png',
			'tpltypename'=>'1252_index_n4fb',
			'tpldesinfo'=>'大气精美的婚纱摄影行业模板',
			'attr'=>'mix thumb filt bg bgs wedding',
			'sort'=>252,
		),
		array(
			'tpltypeid'=>253,
			'tplview'=>'cate1253.png',
			'tpltypename'=>'1253_index_n4fb',
			'tpldesinfo'=>'大气精美的婚纱摄影行业模板',
			'attr'=>'mix thumb filt bg bgs wedding',
			'sort'=>253,
		),
		array(
			'tpltypeid'=>254,
			'tplview'=>'cate1254.png',
			'tpltypename'=>'1254_index_n4fb',
			'tpldesinfo'=>'大气精美的婚纱摄影行业模板',
			'attr'=>'mix bg bgs filt wedding',
			'sort'=>254,
		),
		array(
			'tpltypeid'=>255,
			'tplview'=>'cate1255.png',
			'tpltypename'=>'1255_index_n4fb',
			'tpldesinfo'=>'大气精美的婚纱摄影行业模板',
			'attr'=>'mix wedding bgs bg filt',
			'sort'=>255,
		),
		array(
			'tpltypeid'=>256,
			'tplview'=>'cate1256.png',
			'tpltypename'=>'1256_index_n4fb',
			'tpldesinfo'=>'左右图文式模版，顶部幻灯片建议使用尺寸为640*320或近似等比例图片；分类图片建议使用450*300或近似等比例图片，请不要使用高度大于或接近于宽度的图片',
			'attr'=>'mix wedding bgs focu thumb',
			'sort'=>256,
		),
		array(
			'tpltypeid'=>257,
			'tplview'=>'cate1257.png',
			'tpltypename'=>'1257_index_n4fb',
			'tpldesinfo'=>'列表式图片模版，缩略图建议使用150*150或近似尺寸比例的图片',
			'attr'=>'mix wedding thumb focu bgs lis',
			'sort'=>257,
		),
		array(
			'tpltypeid'=>258,
			'tplview'=>'cate1258.png',
			'tpltypename'=>'1258_index_n4fb',
			'tpldesinfo'=>'暂无模板描述',
			'attr'=>'mix wedding thumb focu bgs',
			'sort'=>258,
		),
		array(
			'tpltypeid'=>259,
			'tplview'=>'cate1259.png',
			'tpltypename'=>'1259_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix car thumb bgs slip bg',
			'sort'=>259,
		),
		array(
			'tpltypeid'=>260,
			'tplview'=>'cate1260.png',
			'tpltypename'=>'1260_index_n4fb',
			'tpldesinfo'=>'分类图片为正方形300x300px',
			'attr'=>'mix car thumb bgs slip bg filt',
			'sort'=>260,
		),
		array(
			'tpltypeid'=>261,
			'tplview'=>'cate1261.png',
			'tpltypename'=>'1261_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix car thumb bgs slip bg',
			'sort'=>261,
		),
		array(
			'tpltypeid'=>262,
			'tplview'=>'cate1262.png',
			'tpltypename'=>'1262_index_n4fb',
			'tpldesinfo'=>'分类图片为正方形300x300px',
			'attr'=>'mix car thumb bgs slip bg filt',
			'sort'=>262,
		),
		array(
			'tpltypeid'=>263,
			'tplview'=>'cate1263.png',
			'tpltypename'=>'1263_index_n4fb',
			'tpldesinfo'=>'分类图片为正方形300x300px',
			'attr'=>'mix car thumb bgs slip bg bg',
			'sort'=>263,
		),
		array(
			'tpltypeid'=>264,
			'tplview'=>'cate1264.png',
			'tpltypename'=>'1264_index_n4fb',
			'tpldesinfo'=>'分类图片为正方形300x300px',
			'attr'=>'mix car thumb bgs slip bg',
			'sort'=>264,
		),
		array(
			'tpltypeid'=>265,
			'tplview'=>'cate1265.png',
			'tpltypename'=>'1265_index_n4fb',
			'tpldesinfo'=>'分类图片为正方形300x300px',
			'attr'=>'mix car thumb bgs slip filt bg filt',
			'sort'=>265,
		),
		array(
			'tpltypeid'=>266,
			'tplview'=>'cate1266.png',
			'tpltypename'=>'1266_index_n4fb',
			'tpldesinfo'=>'分类图片为正方形300x300px',
			'attr'=>'mix car thumb bgs slip bg filt',
			'sort'=>266,
		),
		array(
			'tpltypeid'=>267,
			'tplview'=>'cate1267.png',
			'tpltypename'=>'1267_index_n4fb',
			'tpldesinfo'=>'大气精美的汽车行业模板',
			'attr'=>'mix car thumb bgs slip bg focu',
			'sort'=>267,
		),
		array(
			'tpltypeid'=>268,
			'tplview'=>'cate1268.png',
			'tpltypename'=>'1268_index_n4fb',
			'tpldesinfo'=>'分类图片为正方形300x300px',
			'attr'=>'mix car thumb bgs slip focu',
			'sort'=>268,
		),
		array(
			'tpltypeid'=>269,
			'tplview'=>'cate1269.png',
			'tpltypename'=>'1269_index_n4fb',
			'tpldesinfo'=>'分类图片为正方形300x300px',
			'attr'=>'mix car thumb bgs slip bg',
			'sort'=>269,
		),
		array(
			'tpltypeid'=>270,
			'tplview'=>'cate1270.png',
			'tpltypename'=>'1270_index_n4fb',
			'tpldesinfo'=>'此模板支持播放音乐，轮换背景图及漂浮小动画，背景图片尺寸为640x1136px，分类不要太多，多了影响整体美观',
			'attr'=>'mix car thumb bgs bg filt',
			'sort'=>270,
		),
		array(
			'tpltypeid'=>271,
			'tplview'=>'cate1271.png',
			'tpltypename'=>'1271_index_n4fb',
			'tpldesinfo'=>'此模板支持播放音乐，轮换背景图及漂浮小动画，背景图片尺寸为640x1136px，分类图标300x300px，分类不要太多，多了影响整体美观',
			'attr'=>'mix car thumb bgs bg filt',
			'sort'=>271,
		),
		array(
			'tpltypeid'=>272,
			'tplview'=>'cate1272.png',
			'tpltypename'=>'1272_index_n4fb',
			'tpldesinfo'=>'此模板支持播放音乐，轮换背景图及漂浮小动画，背景图片尺寸为640x1136px，分类不要太多，多了影响整体美观',
			'attr'=>'mix estate thumb bgs bg filt',
			'sort'=>272,
		),
		array(
			'tpltypeid'=>273,
			'tplview'=>'cate1273.png',
			'tpltypename'=>'1273_index_n4fb',
			'tpldesinfo'=>'此模板支持播放音乐，轮换背景图及漂浮小动画，背景图片尺寸为640x1136px，分类图标300x300px',
			'attr'=>'mix car thumb bgs filt slip bg',
			'sort'=>273,
		),
		array(
			'tpltypeid'=>274,
			'tplview'=>'cate1274.png',
			'tpltypename'=>'1274_index_n4fb',
			'tpldesinfo'=>'分类的图片统一相同尺寸300x300正方形图片，不用做成圆形图片，系统自己会显示为圆形图片',
			'attr'=>'mix hotel thumb bgs bg',
			'sort'=>274,
		),
		array(
			'tpltypeid'=>275,
			'tplview'=>'cate1275.png',
			'tpltypename'=>'1275_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix hotel thumb bgs slip bg',
			'sort'=>275,
		),
		array(
			'tpltypeid'=>276,
			'tplview'=>'cate1276.png',
			'tpltypename'=>'1276_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix hotel thumb bgs slip bg',
			'sort'=>276,
		),
		array(
			'tpltypeid'=>277,
			'tplview'=>'cate1277.png',
			'tpltypename'=>'1277_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix hotel thumb bgs slip bg bg',
			'sort'=>277,
		),
		array(
			'tpltypeid'=>278,
			'tplview'=>'cate1278.png',
			'tpltypename'=>'1278_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix hotel thumb bgs slip bg',
			'sort'=>278,
		),
		array(
			'tpltypeid'=>279,
			'tplview'=>'cate1279.png',
			'tpltypename'=>'1279_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix hotel thumb bgs slip bg focu',
			'sort'=>279,
		),
		array(
			'tpltypeid'=>280,
			'tplview'=>'cate1280.png',
			'tpltypename'=>'1280_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix hotel thumb bgs slip bg focu',
			'sort'=>280,
		),
		array(
			'tpltypeid'=>281,
			'tplview'=>'cate1281.png',
			'tpltypename'=>'1281_index_n4fb',
			'tpldesinfo'=>'此模板支持播放音乐，轮换背景图及漂浮小动画，背景图片尺寸为640x1136px，分类图标300x300px，分类不要太多，多了影响整体美观',
			'attr'=>'mix hotel thumb bgs bg filt',
			'sort'=>281,
		),
		array(
			'tpltypeid'=>282,
			'tplview'=>'cate1282.png',
			'tpltypename'=>'1282_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix tour thumb bgs slip bg',
			'sort'=>282,
		),
		array(
			'tpltypeid'=>283,
			'tplview'=>'cate1283.png',
			'tpltypename'=>'1283_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix tour thumb bgs slip bg',
			'sort'=>283,
		),
		array(
			'tpltypeid'=>284,
			'tplview'=>'cate1284.png',
			'tpltypename'=>'1284_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix tour thumb bgs slip bg bg',
			'sort'=>284,
		),
		array(
			'tpltypeid'=>285,
			'tplview'=>'cate1285.png',
			'tpltypename'=>'1285_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix tour thumb bgs slip bg',
			'sort'=>285,
		),
		array(
			'tpltypeid'=>286,
			'tplview'=>'cate1286.png',
			'tpltypename'=>'1286_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix tour thumb bgs slip bg focu',
			'sort'=>286,
		),
		array(
			'tpltypeid'=>287,
			'tplview'=>'cate1287.png',
			'tpltypename'=>'1287_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix tour thumb bgs slip focu',
			'sort'=>287,
		),
		array(
			'tpltypeid'=>288,
			'tplview'=>'cate1288.png',
			'tpltypename'=>'1288_index_n4fb',
			'tpldesinfo'=>'此模板支持播放音乐，轮换背景图及漂浮小动画，背景图片尺寸为640x1136px，分类图标300x300px',
			'attr'=>'mix tour thumb bgs filt slip bg',
			'sort'=>288,
		),
		array(
			'tpltypeid'=>289,
			'tplview'=>'cate1289.png',
			'tpltypename'=>'1289_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix restaurant thumb bgs slip bg focu',
			'sort'=>289,
		),
		array(
			'tpltypeid'=>290,
			'tplview'=>'cate1290.png',
			'tpltypename'=>'1290_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix restaurant thumb bgs slip focu',
			'sort'=>290,
		),
		array(
			'tpltypeid'=>291,
			'tplview'=>'cate1291.png',
			'tpltypename'=>'1291_index_n4fb',
			'tpldesinfo'=>'此模板支持播放音乐，轮换背景图及漂浮小动画，背景图片尺寸为640x1136px，分类图标300x300px，分类不要太多，多了影响整体美观',
			'attr'=>'mix restaurant thumb bgs bg filt',
			'sort'=>291,
		),
		array(
			'tpltypeid'=>292,
			'tplview'=>'cate1292.png',
			'tpltypename'=>'1292_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix estate thumb bgs slip bg',
			'sort'=>292,
		),
		array(
			'tpltypeid'=>293,
			'tplview'=>'cate1293.png',
			'tpltypename'=>'1293_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix estate thumb bgs slip bg',
			'sort'=>293,
		),
		array(
			'tpltypeid'=>294,
			'tplview'=>'cate1294.png',
			'tpltypename'=>'1294_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix estate thumb bgs slip bg',
			'sort'=>294,
		),
		array(
			'tpltypeid'=>295,
			'tplview'=>'cate1295.png',
			'tpltypename'=>'1295_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix health thumb bgs slip bg',
			'sort'=>295,
		),
		array(
			'tpltypeid'=>296,
			'tplview'=>'cate1296.png',
			'tpltypename'=>'1296_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix health thumb bgs slip bg',
			'sort'=>296,
		),
		array(
			'tpltypeid'=>297,
			'tplview'=>'cate1297.png',
			'tpltypename'=>'1297_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix health thumb bgs slip bg filt',
			'sort'=>297,
		),
		array(
			'tpltypeid'=>298,
			'tplview'=>'cate1298.png',
			'tpltypename'=>'1298_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix health thumb bgs slip bg filt',
			'sort'=>298,
		),
		array(
			'tpltypeid'=>299,
			'tplview'=>'cate1299.png',
			'tpltypename'=>'1299_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix health thumb bgs slip bg bg',
			'sort'=>299,
		),
		array(
			'tpltypeid'=>300,
			'tplview'=>'cate1300.png',
			'tpltypename'=>'1300_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix edu thumb bgs slip bg',
			'sort'=>300,
		),
		array(
			'tpltypeid'=>301,
			'tplview'=>'cate1301.png',
			'tpltypename'=>'1301_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix health thumb bgs slip bg filt',
			'sort'=>301,
		),
		array(
			'tpltypeid'=>302,
			'tplview'=>'cate1302.png',
			'tpltypename'=>'1302_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix health thumb bgs slip filt bg filt',
			'sort'=>302,
		),
		array(
			'tpltypeid'=>303,
			'tplview'=>'cate1303.png',
			'tpltypename'=>'1303_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix edu thumb bgs slip bg',
			'sort'=>303,
		),
		array(
			'tpltypeid'=>304,
			'tplview'=>'cate1304.png',
			'tpltypename'=>'1304_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix edu thumb bgs slip bg',
			'sort'=>304,
		),
		array(
			'tpltypeid'=>305,
			'tplview'=>'cate1305.png',
			'tpltypename'=>'1305_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix edu thumb bgs slip bg bg',
			'sort'=>305,
		),
		array(
			'tpltypeid'=>306,
			'tplview'=>'cate1306.png',
			'tpltypename'=>'1306_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix edu thumb bgs slip bg',
			'sort'=>306,
		),
		array(
			'tpltypeid'=>307,
			'tplview'=>'cate1307.png',
			'tpltypename'=>'1307_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix edu thumb bgs slip bg focu',
			'sort'=>307,
		),
		array(
			'tpltypeid'=>308,
			'tplview'=>'cate1308.png',
			'tpltypename'=>'1308_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix edu thumb bgs slip focu',
			'sort'=>308,
		),
		array(
			'tpltypeid'=>309,
			'tplview'=>'cate1309.png',
			'tpltypename'=>'1309_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix beauty thumb bgs slip bg filt',
			'sort'=>309,
		),
		array(
			'tpltypeid'=>310,
			'tplview'=>'cate1310.png',
			'tpltypename'=>'1310_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix beauty thumb bgs slip bg filt',
			'sort'=>310,
		),
		array(
			'tpltypeid'=>311,
			'tplview'=>'cate1311.png',
			'tpltypename'=>'1311_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix beauty thumb bgs slip bg',
			'sort'=>311,
		),
		array(
			'tpltypeid'=>312,
			'tplview'=>'cate1312.png',
			'tpltypename'=>'1312_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix beauty thumb bgs slip bg',
			'sort'=>312,
		),
		array(
			'tpltypeid'=>313,
			'tplview'=>'cate1313.png',
			'tpltypename'=>'1313_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix beauty thumb bgs slip bg filt',
			'sort'=>313,
		),
		array(
			'tpltypeid'=>314,
			'tplview'=>'cate1314.png',
			'tpltypename'=>'1314_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix beauty thumb bgs slip filt bg filt',
			'sort'=>314,
		),
		array(
			'tpltypeid'=>315,
			'tplview'=>'cate1315.png',
			'tpltypename'=>'1315_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix beauty thumb bgs slip bg bg',
			'sort'=>315,
		),
		array(
			'tpltypeid'=>316,
			'tplview'=>'cate1316.png',
			'tpltypename'=>'1316_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix beauty thumb bgs slip bg',
			'sort'=>316,
		),
		array(
			'tpltypeid'=>317,
			'tplview'=>'cate1317.png',
			'tpltypename'=>'1317_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix beauty thumb bgs slip bg focu',
			'sort'=>317,
		),
		array(
			'tpltypeid'=>318,
			'tplview'=>'cate1318.png',
			'tpltypename'=>'1318_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix beauty thumb bgs slip focu',
			'sort'=>318,
		),
		array(
			'tpltypeid'=>319,
			'tplview'=>'cate1319.png',
			'tpltypename'=>'1319_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix wedding thumb bgs slip bg filt',
			'sort'=>319,
		),
		array(
			'tpltypeid'=>320,
			'tplview'=>'cate1320.png',
			'tpltypename'=>'1320_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix wedding thumb bgs slip bg filt',
			'sort'=>320,
		),
		array(
			'tpltypeid'=>321,
			'tplview'=>'cate1321.png',
			'tpltypename'=>'1321_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix wedding thumb bgs slip bg',
			'sort'=>321,
		),
		array(
			'tpltypeid'=>322,
			'tplview'=>'cate1322.png',
			'tpltypename'=>'1322_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix wedding thumb bgs slip bg',
			'sort'=>322,
		),
		array(
			'tpltypeid'=>323,
			'tplview'=>'cate1323.png',
			'tpltypename'=>'1323_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix wedding thumb bgs slip bg filt',
			'sort'=>323,
		),
		array(
			'tpltypeid'=>324,
			'tplview'=>'cate1324.png',
			'tpltypename'=>'1324_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix wedding thumb bgs slip filt bg filt',
			'sort'=>324,
		),
		array(
			'tpltypeid'=>325,
			'tplview'=>'cate1325.png',
			'tpltypename'=>'1325_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix wedding thumb bgs slip bg bg',
			'sort'=>325,
		),
		array(
			'tpltypeid'=>326,
			'tplview'=>'cate1326.png',
			'tpltypename'=>'1326_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix wedding thumb bgs slip bg',
			'sort'=>326,
		),
		array(
			'tpltypeid'=>327,
			'tplview'=>'cate1327.png',
			'tpltypename'=>'1327_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix wedding thumb bgs slip bg focu',
			'sort'=>327,
		),
		array(
			'tpltypeid'=>328,
			'tplview'=>'cate1328.png',
			'tpltypename'=>'1328_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix wedding thumb bgs slip focu',
			'sort'=>328,
		),
		array(
			'tpltypeid'=>329,
			'tplview'=>'cate1329.png',
			'tpltypename'=>'1329_index_n4fb',
			'tpldesinfo'=>'分类图标为正方形300x300px',
			'attr'=>'mix wedding thumb bgs slip bg',
			'sort'=>329,
		),
		array(
			'tpltypeid'=>330,
			'tplview'=>'cate1330.png',
			'tpltypename'=>'1330_index_n4fb',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'mix thumb focu bg filt slip',
			'sort'=>330,
		),
		array(
			'tpltypeid'=>331,
			'tplview'=>'cate1331.png',
			'tpltypename'=>'1137_index',
			'tpldesinfo'=>'小图标为正方形300x300px。不支持更换颜色风格',
			'attr'=>'bgs thumb focu',
			'sort'=>331,
		),
	);
	
	
return $tpl;

?>