<?php

	$bottomMenu = array(
	
		array(
			'radiogroupid'=>0,
			'view'=>'000.png',
			'name'=>'关闭底部导航',
			'filename'=>'menuStyle0',
			'sort'=>0,
		),
		array(
			'radiogroupid'=>1,
			'view'=>'001.png',
			'name'=>'左侧展开',
			'filename'=>'menuStyle1',
			'sort'=>1,
		),	
		array(
			'radiogroupid'=>2,
			'view'=>'002.png',
			'name'=>'右侧展开',
			'filename'=>'menuStyle2',
			'sort'=>2,
		),	
		array(
			'radiogroupid'=>3,
			'view'=>'003.png',
			'name'=>'左侧滑入',
			'filename'=>'menuStyle3',
			'sort'=>3,
		),	
		array(
			'radiogroupid'=>4,
			'view'=>'004.png',
			'name'=>'右侧滑入',
			'filename'=>'menuStyle4',
			'sort'=>4,
		),	
		array(
			'radiogroupid'=>5,
			'view'=>'005.png',
			'name'=>'左侧底部滑入',
			'filename'=>'menuStyle5',
			'sort'=>5,
		),	
		array(
			'radiogroupid'=>6,
			'view'=>'006.png',
			'name'=>'右侧底部滑入',
			'filename'=>'menuStyle6',
			'sort'=>6,
		),	
		array(
			'radiogroupid'=>7,
			'view'=>'007.png',
			'name'=>'左侧倾斜',
			'filename'=>'menuStyle7',
			'sort'=>7,
		),	
		array(
			'radiogroupid'=>8,
			'view'=>'008.png',
			'name'=>'右侧倾斜',
			'filename'=>'menuStyle8',
			'sort'=>8,
		),	
		array(
			'radiogroupid'=>9,
			'view'=>'009.png',
			'name'=>'底部静止',
			'filename'=>'menuStyle9',
			'sort'=>9,
		),	
		array(
			'radiogroupid'=>10,
			'view'=>'010.png',
			'name'=>'底部静止',
			'filename'=>'menuStyle10',
			'sort'=>10,
		),	
		array(
			'radiogroupid'=>11,
			'view'=>'011.png',
			'name'=>'底部静止',
			'filename'=>'menuStyle11',
			'sort'=>11,
		),	
		array(
			'radiogroupid'=>12,
			'view'=>'012.png',
			'name'=>'底部静止',
			'filename'=>'menuStyle12',
			'sort'=>12,
		),	
		array(
			'radiogroupid'=>13,
			'view'=>'013.png',
			'name'=>'底部静止',
			'filename'=>'menuStyle13',
			'sort'=>13,
		),	
		array(
			'radiogroupid'=>14,
			'view'=>'014.png',
			'name'=>'底部静止',
			'filename'=>'menuStyle14',
			'sort'=>14,
		),	
		array(
			'radiogroupid'=>15,
			'view'=>'015.png',
			'name'=>'右侧展开',
			'filename'=>'menuStyle15',
			'sort'=>15,
		),	
		array(
			'radiogroupid'=>16,
			'view'=>'016.png',
			'name'=>'右侧展开',
			'filename'=>'menuStyle16',
			'sort'=>16,
		),	
		

	);
	
return $bottomMenu;